const fs=require('fs'),path=require('path');
const root=__dirname,cfg=JSON.parse(fs.readFileSync(path.join(root,'brand/site.json'),'utf8')),out=cfg.outputDirectory?path.join(root,cfg.outputDirectory):(cfg.generated?path.join(root,'public'):root);
const snippets=JSON.parse(fs.readFileSync(path.join(root,'brand/shell.json'),'utf8'));
const skip=new Set(['.git','node_modules','brand','content','public','scripts','research']);
function files(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()&&!skip.has(e.name)?files(path.join(d,e.name)):e.isFile()&&e.name.endsWith('.html')?[path.join(d,e.name)]:[])}
function removeOuter(html){const rx=/<!--[\s\S]*?-->|<(script|style)\b[^>]*>[\s\S]*?<\/\1\s*>|<\/?([a-z][\w:-]*)\b[^>]*>/gi,stack=[],ranges=[];let m,remove=null;const voids=new Set(['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr']);while((m=rx.exec(html))){if(!m[2])continue;const tag=m[2].toLowerCase(),closing=m[0].startsWith('</');if(closing){const i=stack.lastIndexOf(tag);if(i>=0)stack.splice(i);if(remove&&remove.tag===tag&&stack.length===remove.depth){ranges.push([remove.start,rx.lastIndex]);remove=null}}else{if(!stack.length&&['header','nav','footer'].includes(tag))remove={tag,start:m.index,depth:0};if(!voids.has(tag)&&!m[0].endsWith('/>'))stack.push(tag)}}for(const [a,b] of ranges.reverse()){const block=html.slice(a,b);if(/^<header/i.test(block)&&/<h1\b/i.test(block)&&!/<nav\b/i.test(block))continue;html=html.slice(0,a)+html.slice(b);}return html}
function brand(html){if(/id="ae-brand-system"/.test(html))return html;html=html.replace(/<head([^>]*)>/i,'<head$1><meta name="theme-color" content="#1b2a4a">');html=html.replace(/<\/head>/i,'<link id="ae-brand-system" rel="stylesheet" href="/assets/ae-ecosystem.css"><link rel="icon" href="/assets/ae-favicon.svg" type="image/svg+xml"><script defer src="/assets/ae-ecosystem.js"></script></head>');html=html.replace(/<body([^>]*)>([\s\S]*?)<\/body>/i,(_,attr,body)=>{body=removeOuter(body);attr=attr.replace(/\sstyle="[^"]*"/gi,'');if(/class=/.test(attr))attr=attr.replace(/class="([^"]*)"/i,(_,c)=>'class="'+c+' ae-site"');else attr+=' class="ae-site"';if(!/<main\b/i.test(body))body='<main id="main-content" class="ae-content-old">'+body+'</main>';else body=body.replace(/<main([^>]*)>/i,(_,a)=>'<main'+(a.includes('id=')?a:a+' id="main-content"')+'>');const id=(body.match(/<main[^>]*\bid="([^"]+)"/i)||[])[1]||'main-content';return '<body'+attr+'>'+snippets.header.replace('#main-content','#'+id)+body+snippets.footer+'</body>'});return html}
const assets=path.join(out,'assets');fs.mkdirSync(assets,{recursive:true});for(const f of ['ae-ecosystem.css','ae-ecosystem.js','ae-tax-logo.png','ae-favicon.svg'])fs.copyFileSync(path.join(root,'brand',f),path.join(assets,f));
for(const f of files(out)){if(/^google[a-z0-9]+\.html$/.test(path.basename(f)))continue;fs.writeFileSync(f,brand(fs.readFileSync(f,'utf8')))}
const pageDir=path.join(root,'brand/pages');function copy(d,rel=''){for(const e of fs.readdirSync(d,{withFileTypes:true})){const r=path.join(rel,e.name);if(e.isDirectory())copy(path.join(d,e.name),r);else{fs.mkdirSync(path.dirname(path.join(out,r)),{recursive:true});fs.copyFileSync(path.join(d,e.name),path.join(out,r))}}}copy(pageDir);
const sitemap=path.join(out,'sitemap.xml');let xml=fs.readFileSync(sitemap,'utf8');const urls=JSON.parse(fs.readFileSync(path.join(root,'brand/new-urls.json'),'utf8'));for(const u of urls)if(!xml.includes('<loc>'+u+'</loc>'))xml=xml.replace('</urlset>','<url><loc>'+u+'</loc><lastmod>2026-10-10</lastmod></url></urlset>');fs.writeFileSync(sitemap,xml);const home=cfg.domain;fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\n\nSitemap: https://'+home+'/sitemap.xml\n');console.log(JSON.stringify({brand:cfg.label,pages:files(out).length,curated:urls.length}));
